### PR TITLE
Update readme files

### PR DESCRIPTION
**Pull request by mhucka**
## Description

Updates to the README file

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated all documentation necessary.
- [x] I have checked spelling in (new) comments.

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Comment by skeating** [comment]
Hey Frank, why is even trying a Travis ruby build ??

**Comment by fbergmann** [comment]
@skeating  travis failed, since we normally distribute the readme.txt file, but now it is no longer there, and so it rightfully fails to prepare to copy it for distribution later on. 

`CMake Error at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/CPack.cmake:508 (message):
  CPack package description file:
  "/home/travis/build/sbmlteam/libsbml/README.txt" could not be found.
Call Stack (most recent call first):
  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/CPack.cmake:512 (cpack_check_file_exists)
  CMakeLists.txt:167 (include)`

so that line in the script will have to be modified.

**Comment by fbergmann** [comment]
i think the easiest fix would be for the cmake script to just distribute the markdown file.

**Review by fbergmann — APPROVED** [review]
the build is now working again for me

**Comment by mhucka** [comment]
To explain today's commit: when I added README.md and removed README.txt, I stupidly forgot that I had started a directory under docs/historical/ to retain files like that. So I checked out a copy of README.txt again and added it to docs/historical/. The weird timeline is because it came after Frank's fix for the build.

**Comment by mhucka** [comment]
To explain today's commit: when I added README.md and removed README.txt, I forgot that I had started a directory under docs/historical/ to retain files like that. So I checked out a copy of README.txt again and added it to docs/historical/. Then I realized that I _had_ already saved a copy of the readme file, just not under the name that first came to mind. So I removed the 2nd copy.

**Pull request merged**
