### PR TITLE
Fbc v3

### PR DESCRIPTION
**Pull request by skeating**
## Description

New fbc v3
not all bindings done
c#, java, python are done

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Change in documentation

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Comment by fbergmann** [comment]
@skeating finished debugging this, basically the additional errors are being logged, since now every element has an additional SBasePlugin from fbc, which means that all unexpected attributes, will now be once logged by the core (i.e `SBase::readAttributes`) and then again by the package `SBasePlugin::readAttributes`.

**Comment by skeating** [comment]
@fbergmann I have got reading and writing of fbc v3 going except for on a Document - see test in TestWriteFbcExtension
I havent sorted/tested validation fully but probably wont get time in the next few weeks

**Review by fbergmann — APPROVED** [review]
that does look fine to me, and yes the document plugin is handled completely different, so i didnt' expect setting kvp's there.

**Comment by fbergmann** [comment]
the test failed because of a timeout when installing dependencies, rerunning it

**Pull request merged**
