### PR TITLE
Cmake find modules

### PR DESCRIPTION
**Pull request by fbergmann**
## Description
The cmake build gives several warnings currently, the exported target cmake files contain full path to libraries, which makes them not relocatable. 

This PR sorts these points, for a couple of libraries for now. 

## Motivation and Context
Make it easier to link against libSBML when importing CMAKE targets. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Change in documentation

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Comment by fbergmann** [comment]
(the test failure of the one osx run was because of a timeout of the build machine)

**Comment by fbergmann** [comment]
apparently the ubuntu 18.04 runners don't work right now either. but I've verified that this is not an issue. with the changes I made.

**Comment by giordano** [comment]
> apparently the ubuntu 18.04 runners don't work right now either. but I've verified that this is not an issue. with the changes I made.

Running `sudo apt-get update`, to update the list of packages, before `sudo apt-get install` should help.  There has been a security update for `expat` a few days ago: http://changelogs.ubuntu.com/changelogs/pool/main/e/expat/expat_2.2.5-3ubuntu0.7/changelog

**Comment by fbergmann** [comment]
that would increase the build time quite a bit, but could be done. However, this has nothing to do with this pr.

**Comment by giordano** [comment]
> that would increase the build time quite a bit

Why?  `apt-get update` should take a few seconds.  To be clear, it doesn't update all the packages in the environment (that's `apt-get upgrade`), only the list of the available packages in the repositories, which is the issue here: the package manager is trying to install the wrong version of a package.

**Review by skeating — APPROVED** [review]

**Pull request merged**
