### PR TITLE
Find R include path dynamically in CI system

### PR DESCRIPTION
**Pull request by alessandrofelder**
## Description
This PR avoids having a hard-coded R version in the R include path, by searching for it dynamically.
Addresses #180 .

## Motivation and Context
The Windows Server of the CI pipeline regularly updates the underlying R version, which causes the nightly builds to fail. This PR avoids this happening in the future. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Change in documentation

## Checklist:

- [x] I have updated all documentation necessary.
- [x] I have checked spelling in (new) comments.

## Testing
- [ ] Testing is done automatically and codecov shows test coverage
- [x] This cannot be tested automatically. I used the `tmate` action to ssh into the GitHub Actions runner instance and check that the commands I added to Windows successfully find the correct R include path without hardcoding of the version. The longer PR tests should also show that the R version is found correctly on Windows.

### CODE REVIEW

**Comment by alessandrofelder** [comment]
Not sure why Git/GitHub thinks I have coauthored some of those commits. But I think the changes are sensible 🤞

**Comment by alessandrofelder** [comment]
Mac R builds still fail, to be addressed with #176 .

**Comment by alessandrofelder** [comment]
[Raw logs of a Windows build in the extensive CI build for this PR](https://pipelines.actions.githubusercontent.com/WK6qkosQV4e3yxj9ADDMnkaXzGjcrO5irGb3tEvYYtLhG0zubJ/_apis/pipelines/1/runs/576/signedlogcontent/15?urlExpires=2021-11-26T12%3A00%3A23.0749931Z&urlSigningMethod=HMACV1&urlSignature=L6o0Dfpw0RoQeZZuOfaap3%2F5Trq7CklOPOeHu%2FEIlRs%3D) show
`2021-11-26T11:09:33.3155077Z   R_INCLUDE_PATH: /c/Program Files/R/R-4.1.2/include`
so the R include path is found correctly without hard-coding the version 🙂

**Review by fbergmann — APPROVED** [review]
looks all good to me, if anything the version number for the resulting archive should some time be extracted from the version.txt file in the root folder, then we wont have to upgrade it manually every time. but that can be another pr

**Pull request merged**
